name: Moodle Plugin CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-22.04
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
    
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2']
        moodle-branch: ['MOODLE_405_STABLE']
        database: [pgsql]
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          path: plugin
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: pgsql, zip, gd, xmlrpc, soap, intl, json, mbstring
          ini-values: max_input_vars=5000
          coverage: none
      
      - name: Initialise moodle-plugin-ci
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4
          echo $(cd ci/bin; pwd) >> $GITHUB_PATH
          echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
          sudo locale-gen en_AU.UTF-8
          echo "NVM_DIR=$HOME/.nvm" >> $GITHUB_ENV
      
      - name: Install moodle-plugin-ci
        run: |
          moodle-plugin-ci install --plugin ./plugin/lib/editor/tiny/plugins/elediastyles --db-host=127.0.0.1
        env:
          DB: pgsql
          MOODLE_BRANCH: MOODLE_405_STABLE
      
      - name: PHP Lint
        if: always()
        run: moodle-plugin-ci phplint
      
      - name: Moodle Code Checker
        if: always()
        run: moodle-plugin-ci phpcs --max-warnings 0
      
      - name: Validating
        if: always()
        run: moodle-plugin-ci validate
      
      - name: Check upgrade savepoints
        if: always()
        run: moodle-plugin-ci savepoints
      
      - name: Mustache Lint
        if: always()
        run: moodle-plugin-ci mustache
      
      - name: Grunt
        if: always()
        run: moodle-plugin-ci grunt --max-lint-warnings 0
      
      - name: PHPUnit tests
        if: always()
        run: moodle-plugin-ci phpunit --fail-on-warning
      
      - name: Behat features
        if: always()
        run: moodle-plugin-ci behat --profile chrome
